name: "Synology Uploader"
description: "Upload artifacts to your Synology FileStation"
branding:
  icon: box
  color: black
inputs:
  host:
    description: "Host name of the Synology NAS, including the protocol (HTTP/HTTPS) and the port, without trailing slash"
    required: true
  sharing_id:
    description: "Sharing ID provided by Synology"
    required: true
  password:
    description: "The password for the file request, if defined"
  file:
    description: "The file to upload"
    required: true
  uploader_name:
    description: "Uploader name"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{inputs.host}}
    - ${{inputs.password}}
    - ${{inputs.sharing_id}}
    - ${{inputs.uploader_name}}
    - ${{inputs.file}}
