name: Test Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: upload
        uses: ./
        with: 
          host: ${{secrets.NAS_HOST}}
          sharing_id: 'gDVIsFgc6'
          uploader_name: 'test_name'
          password: ${{secrets.NAS_PASSWD}}
          file: 'hello.txt'
